services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
volumes:
  pgdata:
